services:
  - type: web
    name: django-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn icanhelp.wsgi:application"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"