# Generated by Django 4.2.21 on 2025-06-13 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='UserCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('points_per_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=10)),
                ('availability', models.JSONField(default=dict)),
                ('competences_desired', models.ManyToManyField(blank=True, related_name='user_desired', to='api.usercompetence')),
                ('competences_persornal', models.ManyToManyField(blank=True, related_name='user_personal', to='api.usercompetence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDiscussionMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastOpenDiscussionAt', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofil')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('Image', 'Image'), ('File', 'File')], default='text', max_length=20)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.discussion')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageSends', to='api.userprofil')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPT', 'Accepté'), ('REJECT', 'Refusé')], default='PENDING', max_length=20)),
                ('message', models.TextField()),
                ('competences_desired', models.ManyToManyField(blank=True, related_name='invitation_competences_desired', to='api.usercompetence')),
                ('competences_persornal', models.ManyToManyField(blank=True, related_name='invitation_competences_personal', to='api.usercompetence')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendInvitations', to='api.userprofil')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedInvitations', to='api.userprofil')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createDiscussions', to='api.userprofil'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='lastMessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_of_last', to='api.message'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='discussions', to='api.userprofil'),
        ),
    ]
