# Generated by Django 5.1.6 on 2025-03-25 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('Image', 'Image'), ('File', 'File')], default='text', max_length=20)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.discussion')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='lastMessage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_of_last', to='api.message'),
        ),
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competences_desired', models.ManyToManyField(blank=True, related_name='user_desired', to='api.competence')),
                ('competences_persornal', models.ManyToManyField(blank=True, related_name='user_personal', to='api.competence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPT', 'Accepté'), ('REJECT', 'Refusé')], default='PENDING', max_length=20)),
                ('message', models.TextField()),
                ('competences_desired', models.ManyToManyField(blank=True, related_name='invitation_competences_desired', to='api.competence')),
                ('competences_persornal', models.ManyToManyField(blank=True, related_name='invitation_competences_personal', to='api.competence')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendInvitations', to='api.userprofil')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedInvitations', to='api.userprofil')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createDiscussions', to='api.userprofil'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='discussions', to='api.userprofil'),
        ),
    ]
