# Generated by Django 4.2.21 on 2025-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='adress',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
