# Generated by Django 5.1.6 on 2025-02-07 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_discussion_message_userprofil_discussion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='user',
        ),
        migrations.AddField(
            model_name='discussion',
            name='createdBy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='createDiscussions', to='api.userprofil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='discussion',
            name='state',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPT', 'Accepté'), ('REJECT', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receivedDiscussions', to='api.userprofil'),
            preserve_default=False,
        ),
    ]
