# Generated by Django 4.2.21 on 2025-07-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofil_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompetence',
            old_name='points_per_hour',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='usercompetence',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
