# Generated by Django 5.1.6 on 2025-02-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_discussion_user_discussion_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='state',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPT', 'Accepté'), ('REJECT', 'Refusé')], default='PENDING', max_length=20),
        ),
    ]
