# Generated by Django 4.2.21 on 2025-07-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_points_per_hour_usercompetence_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='userprofil',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='competences_desired',
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='competences_persornal',
        ),
        migrations.AddField(
            model_name='usercompetence',
            name='type',
            field=models.CharField(choices=[('PERSONAL', 'Personnelle'), ('DESIRED', 'A apprendre')], default='PERSONAL', max_length=30),
        ),
        migrations.AddField(
            model_name='usercompetence',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='api.userprofil'),
            preserve_default=False,
        ),
    ]
