# Generated by Django 4.2.21 on 2025-07-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_options_alter_userprofil_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='competences_desired',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='competences_persornal',
        ),
        migrations.AddField(
            model_name='invitation',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiverPoints',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiver_competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_competences_receive', to='api.usercompetence'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='senderPoints',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender_competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_competences_send', to='api.usercompetence'),
        ),
    ]
