# Generated by Django 4.2.21 on 2025-05-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdiscussionmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscussionmetadata',
            name='lastOpenDiscussionAt',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
