# Generated by Django 5.1.6 on 2025-03-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_discussion_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='type',
            field=models.BooleanField(choices=[(0, 'Personal'), (1, 'Desired')], default=0),
        ),
    ]
