# Generated by Django 5.1.6 on 2025-03-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_competence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='type',
        ),
    ]
