# Generated by Django 4.2.21 on 2025-06-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userdiscussionmetadata_lastopendiscussionat'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
