# Generated by Django 4.2.21 on 2025-07-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_invitation_competences_desired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(default='', help_text="Nom de l’icône Flutter (ex: 'sports_soccer')", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercompetence',
            name='type',
            field=models.CharField(choices=[('personal', 'Personnelle'), ('desired', 'A apprendre')], default='personal', max_length=30),
        ),
    ]
