# Generated by Django 4.2.21 on 2025-07-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_icon_name_alter_usercompetence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
    ]
