# Generated by Django 5.1.6 on 2025-03-04 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_competence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='user2',
        ),
        migrations.AddField(
            model_name='discussion',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receivedDiscussions', to='api.userprofil'),
            preserve_default=False,
        ),
    ]
