# Generated by Django 4.2.21 on 2025-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_discussion_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='availability',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
