# Generated by Django 4.2.21 on 2025-08-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='api.discussion'),
        ),
    ]
