# Generated by Django 4.2.21 on 2025-06-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usercompetence_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='competences_desired',
            field=models.ManyToManyField(blank=True, related_name='user_desired', to='api.usercompetence'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='competences_persornal',
            field=models.ManyToManyField(blank=True, related_name='user_personal', to='api.usercompetence'),
        ),
    ]
