# Generated by Django 4.2.21 on 2025-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invitation_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='pointsToLose',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='pointsToWin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
