# Generated by Django 4.2.21 on 2025-08-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofil_pointstolose_userprofil_pointstowin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='pointsToLose',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='pointsToWin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
