# Generated by Django 4.2.21 on 2025-06-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userprofil_competences_desired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.category'),
            preserve_default=False,
        ),
    ]
