# Generated by Django 4.2.21 on 2025-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_competence_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompetence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercompetence',
            name='points_per_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
