# Generated by Django 4.2.21 on 2025-09-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofil_pointstolose_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompetence',
            options={},
        ),
        migrations.AddField(
            model_name='invitation',
            name='type',
            field=models.CharField(choices=[('LEARN', 'Learn'), ('TEACH', 'Teach')], default='LEARN', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='state',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPT', 'Accepté'), ('REJECT', 'Refusé'), ('VALIDATE', 'Terminé')], default='PENDING', max_length=20),
        ),
    ]
