# Generated by Django 4.2.21 on 2025-06-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usercompetence_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompetence',
            name='competence',
        ),
        migrations.AddField(
            model_name='usercompetence',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercompetence',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='competences_desired',
            field=models.ManyToManyField(blank=True, related_name='invitation_competences_desired', to='api.usercompetence'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='competences_persornal',
            field=models.ManyToManyField(blank=True, related_name='invitation_competences_personal', to='api.usercompetence'),
        ),
        migrations.DeleteModel(
            name='Competence',
        ),
    ]
