# Generated by Django 6.0.2 on 2026-02-28 11:38

import api.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usercompetence_options_invitation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=api.utils.upload_paths.get_upload_path),
        ),
    ]
