# Generated by Django 6.0.2 on 2026-03-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompetence',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
