# Generated by Django 6.0.2 on 2026-03-03 00:45

import api.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_usercompetence_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=api.utils.upload_paths.get_upload_category_path),
        ),
    ]
