# Generated by Django 6.0.2 on 2026-03-03 06:54

import api.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompetence',
            name='file',
        ),
        migrations.AddField(
            model_name='usercompetence',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=api.utils.upload_paths.get_upload_competence_image__path),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
