# Generated by Django 6.0.2 on 2026-03-04 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_usercompetence_file_usercompetence_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='receiverPoints',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='receiver_competence',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='senderPoints',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='sender_competence',
        ),
        migrations.AddField(
            model_name='invitation',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usercompetence'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='invitation',
            name='pointsWasChange',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
