# Generated by Django 6.0.3 on 2026-03-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_invitation_receiverpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='scheduledAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='scheduledBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_invitations', to='api.userprofil'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='scheduledPlace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='validatedByCreator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='validatedByReceiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='state',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPT', 'Accepté'), ('REJECT', 'Refusé'), ('VALIDATE', 'Terminé'), ('SCHEDULED', 'RDV confirmé')], default='PENDING', max_length=20),
        ),
    ]
