# Generated by Django 6.1.1 on 2026-09-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_availability_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='cancelReason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invitation',
            name='cancelledBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelledInvitations', to='api.userprofil'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='state',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPT', 'Accepté'), ('REJECT', 'Refusé'), ('VALIDATE', 'Terminé'), ('CANCEL', 'Annulé')], default='PENDING', max_length=20),
        ),
    ]
