services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    entrypoint: /app/entrypoint.sh gunicorn
    networks:
      - traefik-net
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skillou-api.rule=Host(`api.skillou.com`)"
      - "traefik.http.routers.skillou-api.entrypoints=websecure"
      - "traefik.http.routers.skillou-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.skillou-api.loadbalancer.server.port=8000"

  db:
    image: mysql:8.4
    container_name: skillou_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  traefik-net:
    external: true   # créé par traefik/docker-compose.yml
  internal:
    driver: bridge

volumes:
  mysql_data:
